[service]
    address = ":8080"
[template]
    path = "./templates"
[database]
    dsn = "./storage/db/go-whisper.db"
[logger]
    path = "./storage/logs/common.log"
[secure]
    # resetToken 重置用户密码所需口令(必须128个字符)
    resetToken = ""
[tencentyun]
    [tencentyun.cos]
        url = ""
        secretID = ""
        secretKey = ""